// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlxyowdvucyweyfkgyce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseHlvd2R2dWN5d2V5ZmtneWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Njk1ODksImV4cCI6MjA1NzE0NTU4OX0.AkTtclyDQ85Un6C0bObGHl2n5f2fLr5hFS4gnAl_d_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);